### ISSUE TITLE
Link connections seem to become untrackable after Sketch app updates

### ISSUE THREAD

**Issue by kolywater** [abynim/UserFlows.sketchplugin#116]
I have a bunch of connections in my pages, and after Sketch does a version release, When I redraw the connections or modify a connection, all of the previous connections are deleted. Perhaps the method for tracking the connections changed?

This has happened a few times now, and means I have to redraw all of the connections post-update.

Attaching screencap: https://www.dropbox.com/s/i0t7lxr9pjvmcm5/user%20flows%20connections%20deleted.mov?dl=0

**Comment by abynim** [comment]
@kolywater have you tried this with the latest version of the plugin? I updated it two days back to make it compatible with Sketch 48, and this issue _should_ be fixed in the latest update.

**Comment by dejot** [comment]
Hi Abynim - I think the problem itself is not so complicated, the fact is, that UF is not working in the actual Sketch Version 48.1

I have the problem, that if I select a symol and an artboard and hit cmd+shift+M the info-bar with the message "Link created..." appears, but nothing more happens.

regards

**Comment by abynim** [comment]
@dejot in that case, run the `Redraw Connections` command and all your connections should reappear. Let me know if that fixes the problem. 
If you're seeing the `Link created...` message it means the links are being created but not displayed because you may have previously hidden the links. The plugin assumes you want to keep the links hidden, until you run the`Redraw Connections` command again.

**Comment by dejot** [comment]
Great. Many thanks - everything works fine now!
All the best!
Best regards
Darko

**Comment by kolywater** [comment]
@abynim thanks for the quick response. I'm not able to repro the issue now. I'll close for now and reopen if I experience it again. thanks for all the hard work on this plugin. it's a lifesaver.
