### ISSUE TITLE
UserFlows breaking my entire UX map

### ISSUE THREAD

**Issue by chrissy-pipetti** [abynim/UserFlows.sketchplugin#166]
Hi there—every time I use one particular page in my Sketch file, the user flows are moved away from my artboards and my artboards all appear blank. I can click on the elements within the artboards, but cannot do anything else. I can't redraw connections, or use the plugin at all only on this particular page. My other flows are all fine. I've restarted Sketch, reinstalled the latest version of the plugin, all to no avail. I need to provide these to a client today. Please help!
![image](https://user-images.githubusercontent.com/18538005/57868869-c811f100-77d1-11e9-91a3-8fb4c5f78177.png)

**Comment by abynim** [comment]
@chrissy-pipetti would it be possible to privately send me the Sketch document with just this page? That would be the fastest way for me to debug the issue. You can email it to abynimbalkar at gmail. 

If that's not possible, try this: 
- Open Console.app from `Applications > Utilities` 
- Filter the logs by typing Sketch in the search field
- Try to Redraw Connections on that page
- See if anything shows up in the logs

If you prefer to discuss over email instead of Github, that's fine too. Hope you're not missing your deadline!
