### ISSUE TITLE
Please fix 🙏🏼

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#185]
Sketch's updates mean this no longer works 😢 

This was the best flow plugin available. 

Please help

Thank you

**Comment by kamiyarsanau** [comment]
Bump, same here, would love for it to be updated in working condition

**Comment by MamaMac** [comment]
Please don't abandon this plugin!!! Our entire team depends on it. THERE IS NO OTHER PLUGIN LIKE IT!! Right now it blows up: it keeps re-adding flow lines, it remembers old ones no matter how many times they are deleted. Remove all on current page doesn't work. Every time I add one arrow, it duplicates all of them. Please Please Please fix this because it is such a great plugin. At least reply to folks and let them know you have either moved on from this and will no longer be updating it or let us know you are working on a fix. Thank you. I can't emphasize enough how much I need this plugin right now.

**Comment by samhails** [comment]
Please please please - same here, i completely depend on this for documentation, there is no substitute.

**Comment by abynim** [comment]
Should be fixed in v 2.3.9. Please test if you get a chance. Thanks!

**Comment by ghost** [comment]
AMAZING!!!!! 🥰 🥰 🥰 🥰 🥰 🥰 🥰 🥰 🥰 🥰

**Comment by samhails** [comment]
You are absolutely the best 👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

Sent via mobile, may contain typos courtesy of autocorrect.
